# Generated by Django 3.1.7 on 2021-04-24 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_checkuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckUser',
            new_name='CheckNewUser',
        ),
    ]
